### ISSUE TITLE
Error when adding AbsintheLinter to schema pipeline

### ISSUE THREAD

**Issue by michaelcaterisano** [maartenvanvliet/absinthe_linter#25]
I added AbsintheLinter to my schema pipeline and am seeing an error. Below is the stack trace; any ideas? 

System:
erlang 25.1.2
elixir 1.14.2-otp-25
absinthe 1.7

```
(KeyError) key :name not found in: [:approved, :needs_review, :in_progress, :none]. If you are using the dot syntax, such as map.field, make sure the left-hand side of the dot is a map
    (absinthe_linter 0.1.1) lib/rules/enum_values_sorted_alphabetically.ex:31: anonymous fn/1 in AbsintheLinter.Rules.EnumValuesSortedAlphabetically.sorted_values?/1
    (elixir 1.14.2) lib/enum.ex:3264: anonymous fn/2 in Enum.sort_by/3
    (elixir 1.14.2) lib/enum.ex:1658: Enum."-map/2-lists^map/1-0-"/2
    (elixir 1.14.2) lib/enum.ex:3264: Enum.sort_by/3
    (absinthe_linter 0.1.1) lib/rules/enum_values_sorted_alphabetically.ex:31: AbsintheLinter.Rules.EnumValuesSortedAlphabetically.sorted_values?/1
    (absinthe_linter 0.1.1) lib/rules/enum_values_sorted_alphabetically.ex:19: AbsintheLinter.Rules.EnumValuesSortedAlphabetically.validate_node/1
    (absinthe 1.7.0) lib/absinthe/blueprint/transform.ex:16: anonymous fn/3 in Absinthe.Blueprint.Transform.prewalk/2
    (absinthe 1.7.0) lib/absinthe/blueprint/transform.ex:109: Absinthe.Blueprint.Transform.walk/4
    (elixir 1.14.2) lib/enum.ex:1780: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
    (elixir 1.14.2) lib/enum.ex:1780: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
    (absinthe 1.7.0) lib/absinthe/blueprint/transform.ex:139: anonymous fn/4 in Absinthe.Blueprint.Transform.walk_children/5
    (elixir 1.14.2) lib/enum.ex:2468: Enum."-reduce/3-lists^foldl/2-0-"/3
    (absinthe 1.7.0) lib/absinthe/blueprint/transform.ex:114: Absinthe.Blueprint.Transform.walk/4
    (elixir 1.14.2) lib/enum.ex:1780: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
    (absinthe 1.7.0) lib/absinthe/blueprint/transform.ex:139: anonymous fn/4 in Absinthe.Blueprint.Transform.walk_children/5
    (elixir 1.14.2) lib/enum.ex:2468: Enum."-reduce/3-lists^foldl/2-0-"/3
    (absinthe 1.7.0) lib/absinthe/blueprint/transform.ex:114: Absinthe.Blueprint.Transform.walk/4
    (absinthe 1.7.0) lib/absinthe/blueprint/transform.ex:15: Absinthe.Blueprint.Transform.prewalk/2
    (absinthe_linter 0.1.1) lib/rules/enum_values_sorted_alphabetically.ex:9: AbsintheLinter.Rules.EnumValuesSortedAlphabetically.run/2
    (absinthe 1.7.0) lib/absinthe/pipeline.ex:384: Absinthe.Pipeline.run_phase/3
```

**Comment by maartenvanvliet** [comment]
I think you use the shorthand notation for enums. I'll look into a fix

**Comment by maartenvanvliet** [comment]
I pushed a fix.

It was the shorthand definition of the enum. This yields a different internal representation of the schema leading to bugs like these.
